# App config - Development version
secret_key: glpjht9dPBXQe8mBS9XxDMGLIoHukbpvSNU0FpnZ
frontend_server: bhsclient

# Mail server
mail_server: 'localhost'
mail_port: 25
# mail_username: 'user'
# mail_password: 'sss'

# Data DB
data_db_host: 104.155.92.186
data_db_port: 27017
data_db_name: bhp6

# User DB config
user_db_host: localhost
user_db_port: 27017
user_db_name: bh

# Email config
email_username: bhatfutsot@gmail.com
email_password: 19782013
email_from: info@bh.org.il

# Bucket urls
image_bucket_url: https://storage.googleapis.com/bhs-flat-pics
ftree_bucket_url: https://storage.googleapis.com/bhs-familytrees
video_bucket_url: https://storage.googleapis.com/bhs-videos
# elastic search
elasticsearch_host: bhs-infra
# redis
redis_host: localhost
redis_port: 6379
caching_ttl: 3600
