# App config - Development version
secret_key: glpjht9dPBXQe8mBS9XxDMGLIoHukbpvSNU0FpnZ
security_password_hash: pbkdf2_sha512
#security_password_salt: pjht9dPBXQe8mB
security_password_salt: 68XDri7fdCi1dCkN2Prs

# Data DB
data_db_host: bhs-infra
data_db_port: 27017
data_db_name: bhp6

# User DB config
user_db_host: localhost
user_db_port: 27017
user_db_name: bh

# Email config
email_username: bhatfutsot@gmail.com
email_password: 19782013
email_from: info@bh.org.il

# Bucket urls
image_bucket_url: https://storage.googleapis.com/bhs-flat-pics
ftree_bucket_url: https://storage.googleapis.com/bhs-familytrees
video_bucket_url: https://storage.googleapis.com/bhs-videos

elasticsearch_host: bhs-infra

neo4j_url: http://neo4j:bhonline@146.148.125.14:7474/db/data
