# App config - Development version
secret_key: glpjht9dPBXQe8mBS9XxDMGLIoHukbpvSNU0FpnZ
security_password_hash: pbkdf2_sha512
security_password_salt: pjht9dPBXQe8mB

# DB Config
db_host: localhost
db_port: 27017
db_name: bh

